import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { TelegramThemeProvider } from "@/components/providers/telegram-theme-provider";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer/footer";
import { WebAppProvider } from "@/context/WebAppContext";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import { StartParamHandler } from "@/components/tools/StartParamHandler";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               <TelegramThemeProvider>
                  <WebAppProvider>
                     <Suspense fallback={null}>
                        <StartParamHandler />
                     </Suspense>
                     <Header />
                     <main className="py-26">{children}</main>

                     <Toaster
                        position="top-center"
                        toastOptions={{
                           style: {
                              marginTop: "70px",
                           },
                        }}
                     />
                     <Footer />
                  </WebAppProvider>
               </TelegramThemeProvider>
            </ThemeProvider>
         </body>
      </html>
   );
}
